In [ ]:
!pip install tensorflow~=2.1.0 pandas sklearn keras

In [1]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from py_session import py_session
import time
try:
  # Use the %tensorflow_version magic if in colab.
  %tensorflow_version 2.x
except Exception:
  pass

import tensorflow as tf
from tensorflow.keras.utils import to_categorical
import numpy as np
import collections
from sklearn.utils import shuffle

In [3]:

le= LabelEncoder()

In [4]:
datasetScenearioA120 = pd.read_csv("datasetScenearioA120.csv", header=None, 
 names=['duration',
 'total_fiat',
 'total_biat',
 'min_fiat',
 'min_biat',
 'max_fiat',
 'max_biat',
 'mean_fiat',
 'mean_biat',
 'flowPktsPerSecond',
 'flowBytesPerSecond',
 'min_flowiat',
 'max_flowiat',
 'mean_flowiat',
 'std_flowiat',
 'min_active',
 'mean_active',
 'max_active',
 'std_active',
 'min_idle',
 'mean_idle',
 'max_idle',
 'std_idle',
 'class'])

In [5]:
datasetScenearioA120['encoded_class']=le.fit_transform(datasetScenearioA120['class'])

In [6]:
le.classes_

array(['Non-VPN', 'VPN'], dtype=object)

In [7]:
le_name_mapping = dict(zip(le.classes_, le.transform(le.classes_)))
print(le_name_mapping)

{'Non-VPN': 0, 'VPN': 1}


In [8]:
datasetScenearioA120=datasetScenearioA120.drop(columns=['class'])

In [9]:
datasetA120Norm=((datasetScenearioA120-datasetScenearioA120.mean())/(datasetScenearioA120.std()))

In [10]:
datasetA120Norm['encoded_class']=datasetScenearioA120['encoded_class']

In [12]:
datasetA120Norm

duration  total_fiat  total_biat  min_fiat  min_biat  max_fiat  \
0      1.387643   -0.311477   -0.276861  0.628009  0.823722 -0.411613   
1      1.433055   -0.311477   -0.276861  0.628704  0.818574 -0.409091   
2      0.876661   -0.311476   -0.276861  0.261788  0.379124 -0.376589   
3      0.396602   -0.311477   -0.276861  0.320534  0.449830 -0.396896   
4      1.441082    1.925923    2.154681  0.452196  0.613841  1.628258   
...         ...         ...         ...       ...       ...       ...   
10777 -0.849416   -0.311478   -0.276861 -0.564611 -0.609334 -0.444381   
10778 -0.847825   -0.311478   -0.276861 -0.564611 -0.609334 -0.444381   
10779 -0.450740    1.254690   -0.276861  0.147106 -0.609334  1.006467   
10780 -0.848151   -0.311467   -0.276861 -0.561198 -0.605174 -0.440898   
10781 -0.848186   -0.311471   -0.276861 -0.561222 -0.605227 -0.440924   

       max_biat  mean_fiat  mean_biat  flowPktsPerSecond  ...  std_flowiat  \
0     -0.392982  -0.162273  -0.155449           0.649243  ...    -0.355567   
1     -0.394245  -0.155295  -0.162247           0.607625  ...    -0.354658   
2     -0.349008  -0.042972   0.009202           0.199013  ...    -0.263476   
3     -0.378565  -0.100082  -0.083194           0.187662  ...    -0.312051   
4      1.811737  -0.381014  -0.464994          -0.058262  ...     0.944604   
...         ...        ...        ...                ...  ...          ...   
10777 -0.434757  -0.381086  -0.465127          -0.077179  ...    -0.524469   
10778 -0.434757  -0.381086  -0.465127          -0.077179  ...    -0.524469   
10779 -0.434757  -0.381086  -0.465127          -0.077179  ...     0.650789   
10780 -0.432209  -0.374869  -0.458354          -0.073396  ...    -0.519675   
10781 -0.432239  -0.374909  -0.458444          -0.073396  ...    -0.519720   

       min_active  mean_active  max_active  std_active  min_idle  mean_idle  \
0       -0.378909    -0.325365    0.526630    0.521968 -0.381806  -0.351999   
1       -0.376179    -0.345179    0.524956    0.468308 -0.382291  -0.360140   
2       -0.331239    -0.176311    0.190405    0.661566 -0.374314  -0.195001   
3       -0.371975    -0.201415    0.239987    0.728475 -0.377779  -0.223393   
4        0.600347     0.496862    0.359364   -0.368088  0.610032   0.508947   
...           ...          ...         ...         ...       ...        ...   
10777   -0.425529    -0.512487   -0.581572   -0.368185 -0.418916  -0.501611   
10778   -0.425529    -0.512487   -0.581572   -0.368185 -0.418916  -0.501611   
10779   -0.376570    -0.159215    0.032137    1.133178 -0.369720  -0.146733   
10780   -0.425529    -0.512487   -0.581572   -0.368185 -0.418916  -0.501611   
10781   -0.425529    -0.512487   -0.581572   -0.368185 -0.418916  -0.501611   

       max_idle  std_idle  encoded_class  
0      0.545133  0.554642              0  
1      0.541502  0.495028              0  
2      0.200576  0.753111              0  
3      0.255431  0.760556              0  
4      0.380876 -0.358025              0  
...         ...       ...            ...  
10777 -0.566270 -0.358043              0  
10778 -0.566270 -0.358043              0  
10779  0.052654  1.177950              0  
10780 -0.566270 -0.358043              0  
10781 -0.566270 -0.358043              0  

[10782 rows x 24 columns]

In [13]:
datasetA120Norm.describe()

duration    total_fiat    total_biat      min_fiat      min_biat  \
count  1.078200e+04  10782.000000  1.078200e+04  1.078200e+04  1.078200e+04   
mean  -4.217653e-17      0.000000 -2.108827e-17 -1.054413e-17  2.636033e-17   
std    1.000000e+00      1.000000  1.000000e+00  1.000000e+00  1.000000e+00   
min   -8.520228e-01     -0.311478 -2.768612e-01 -5.646108e-01 -6.093342e-01   
25%   -8.499366e-01     -0.311478 -2.768612e-01 -5.645392e-01 -6.093342e-01   
50%   -6.552464e-01     -0.311474 -2.768599e-01 -5.387084e-01 -5.893271e-01   
75%    1.006762e+00     -0.311365 -2.768483e-01  3.968268e-01  4.496270e-01   
max    1.064043e+01      8.638320  9.449509e+00  1.440668e+01  2.385758e+01   

           max_fiat      max_biat     mean_fiat     mean_biat  \
count  1.078200e+04  1.078200e+04  1.078200e+04  1.078200e+04   
mean  -6.326480e-17 -6.326480e-17  1.054413e-17  9.489719e-17   
std    1.000000e+00  1.000000e+00  1.000000e+00  1.000000e+00   
min   -4.443812e-01 -4.347565e-01 -3.810858e-01 -4.651273e-01   
25%   -4.443383e-01 -4.347565e-01 -3.810858e-01 -4.651273e-01   
50%   -4.337278e-01 -4.299450e-01 -3.787320e-01 -4.626343e-01   
75%   -7.288666e-02 -8.100856e-02 -1.451209e-01 -1.257931e-01   
max    1.005699e+01  8.551218e+00  1.841982e+01  1.080186e+01   

       flowPktsPerSecond  ...   std_flowiat    min_active   mean_active  \
count       1.078200e+04  ...  1.078200e+04  1.078200e+04  1.078200e+04   
mean       -1.054413e-17  ...  1.054413e-17 -1.054413e-17  1.581620e-17   
std         1.000000e+00  ...  1.000000e+00  1.000000e+00  1.000000e+00   
min        -7.717930e-02  ... -5.244692e-01 -4.255293e-01 -5.124872e-01   
25%        -7.717930e-02  ... -5.244481e-01 -4.255293e-01 -5.124872e-01   
50%        -7.339585e-02  ... -5.063638e-01 -3.887143e-01 -4.589017e-01   
75%        -5.826205e-02  ...  2.079971e-01 -5.801428e-02  1.974218e-01   
max         8.126701e+01  ...  1.260537e+01  2.014053e+01  1.970814e+01   

         max_active    std_active      min_idle     mean_idle      max_idle  \
count  1.078200e+04  10782.000000  1.078200e+04  1.078200e+04  1.078200e+04   
mean  -1.028053e-16      0.000000 -1.054413e-17 -3.690446e-17 -2.108827e-17   
std    1.000000e+00      1.000000  1.000000e+00  1.000000e+00  1.000000e+00   
min   -5.815716e-01     -0.368185 -4.189158e-01 -5.016114e-01 -5.662702e-01   
25%   -5.815716e-01     -0.368185 -4.189158e-01 -5.016114e-01 -5.662702e-01   
50%   -5.311829e-01     -0.368185 -3.842974e-01 -4.574142e-01 -5.237783e-01   
75%    3.617373e-01     -0.309898 -7.499652e-02  1.743477e-01  3.768319e-01   
max    1.828056e+01     19.337203  2.020213e+01  1.977716e+01  1.841518e+01   

           std_idle  encoded_class  
count  1.078200e+04   10782.000000  
mean   7.644496e-17       0.522259  
std    1.000000e+00       0.499527  
min   -3.580430e-01       0.000000  
25%   -3.580430e-01       0.000000  
50%   -3.580430e-01       1.000000  
75%   -3.208709e-01       1.000000  
max    1.980187e+01       1.000000  

[8 rows x 24 columns]

In [15]:
datasetScenearioA60 = pd.read_csv("datasetScenearioA60.csv", header=None, 
 names=['duration',
 'total_fiat',
 'total_biat',
 'min_fiat',
 'min_biat',
 'max_fiat',
 'max_biat',
 'mean_fiat',
 'mean_biat',
 'flowPktsPerSecond',
 'flowBytesPerSecond',
 'min_flowiat',
 'max_flowiat',
 'mean_flowiat',
 'std_flowiat',
 'min_active',
 'mean_active',
 'max_active',
 'std_active',
 'min_idle',
 'mean_idle',
 'max_idle',
 'std_idle',
 'class'])

In [16]:
datasetScenearioA60['encoded_class']=le.fit_transform(datasetScenearioA60['class'])

In [17]:
datasetScenearioA60=datasetScenearioA60.drop(columns=['class'])

In [18]:

datasetA60Norm=((datasetScenearioA60-datasetScenearioA60.mean())/(datasetScenearioA60.std()))

In [19]:
datasetA60Norm['encoded_class']=datasetScenearioA60['encoded_class']

In [24]:
datasetScenearioA30 = pd.read_csv("datasetScenearioA30.csv", header=None, 
 names=['duration',
 'total_fiat',
 'total_biat',
 'min_fiat',
 'min_biat',
 'max_fiat',
 'max_biat',
 'mean_fiat',
 'mean_biat',
 'flowPktsPerSecond',
 'flowBytesPerSecond',
 'min_flowiat',
 'max_flowiat',
 'mean_flowiat',
 'std_flowiat',
 'min_active',
 'mean_active',
 'max_active',
 'std_active',
 'min_idle',
 'mean_idle',
 'max_idle',
 'std_idle',
 'class'])

In [25]:
datasetScenearioA30['encoded_class']=le.fit_transform(datasetScenearioA30['class'])

In [26]:
datasetScenearioA30=datasetScenearioA30.drop(columns=['class'])

In [27]:
datasetA30Norm=((datasetScenearioA30-datasetScenearioA30.mean())/(datasetScenearioA30.std()))

In [28]:
datasetA30Norm['encoded_class']=datasetScenearioA30['encoded_class']

In [33]:
datasetScenearioA15 = pd.read_csv("datasetScenearioA15.csv", header=None, 
 names=['duration',
 'total_fiat',
 'total_biat',
 'min_fiat',
 'min_biat',
 'max_fiat',
 'max_biat',
 'mean_fiat',
 'mean_biat',
 'flowPktsPerSecond',
 'flowBytesPerSecond',
 'min_flowiat',
 'max_flowiat',
 'mean_flowiat',
 'std_flowiat',
 'min_active',
 'mean_active',
 'max_active',
 'std_active',
 'min_idle',
 'mean_idle',
 'max_idle',
 'std_idle',
 'class'])

In [34]:
datasetScenearioA15['encoded_class']=le.fit_transform(datasetScenearioA15['class'])

In [35]:
datasetScenearioA15=datasetScenearioA15.drop(columns=['class'])

In [36]:
datasetA15Norm=((datasetScenearioA15-datasetScenearioA15.mean())/(datasetScenearioA15.std()))

In [37]:
datasetA15Norm['encoded_class']=datasetScenearioA15['encoded_class']

In [40]:
dataNorm=datasetA120Norm

In [41]:
dataNorm=dataNorm.append(datasetA60Norm, ignore_index=True)
dataNorm=dataNorm.append(datasetA30Norm, ignore_index=True)
dataNorm=dataNorm.append(datasetA15Norm, ignore_index=True)

In [42]:
dataNorm

duration  total_fiat  total_biat  min_fiat  min_biat  max_fiat  \
0      1.387643   -0.311477   -0.276861  0.628009  0.823722 -0.411613   
1      1.433055   -0.311477   -0.276861  0.628704  0.818574 -0.409091   
2      0.876661   -0.311476   -0.276861  0.261788  0.379124 -0.376589   
3      0.396602   -0.311477   -0.276861  0.320534  0.449830 -0.396896   
4      1.441082    1.925923    2.154681  0.452196  0.613841  1.628258   
...         ...         ...         ...       ...       ...       ...   
59701 -0.675617   -0.271345   -0.269416 -0.312038 -0.296472 -0.319534   
59702 -0.677088   -0.271345   -0.269416 -0.312038 -0.296472 -0.319534   
59703 -0.675986   -0.271345   -0.269416 -0.312038 -0.296472 -0.319534   
59704 -0.658908   -0.271345   -0.269416 -0.312038 -0.296472 -0.319534   
59705 -0.675398   -0.271345   -0.269416 -0.312038 -0.296472 -0.319534   

       max_biat  mean_fiat  mean_biat  flowPktsPerSecond  ...  std_flowiat  \
0     -0.392982  -0.162273  -0.155449           0.649243  ...    -0.355567   
1     -0.394245  -0.155295  -0.162247           0.607625  ...    -0.354658   
2     -0.349008  -0.042972   0.009202           0.199013  ...    -0.263476   
3     -0.378565  -0.100082  -0.083194           0.187662  ...    -0.312051   
4      1.811737  -0.381014  -0.464994          -0.058262  ...     0.944604   
...         ...        ...        ...                ...  ...          ...   
59701 -0.369323  -0.194815  -0.243745          -0.107057  ...    -0.292869   
59702 -0.369323  -0.194815  -0.243745          -0.106477  ...    -0.292869   
59703 -0.369323  -0.194815  -0.243745          -0.106945  ...    -0.292869   
59704 -0.369323  -0.194815  -0.243745          -0.108152  ...    -0.292869   
59705 -0.369323  -0.194815  -0.243745          -0.107116  ...    -0.292869   

       min_active  mean_active  max_active  std_active  min_idle  mean_idle  \
0       -0.378909    -0.325365    0.526630    0.521968 -0.381806  -0.351999   
1       -0.376179    -0.345179    0.524956    0.468308 -0.382291  -0.360140   
2       -0.331239    -0.176311    0.190405    0.661566 -0.374314  -0.195001   
3       -0.371975    -0.201415    0.239987    0.728475 -0.377779  -0.223393   
4        0.600347     0.496862    0.359364   -0.368088  0.610032   0.508947   
...           ...          ...         ...         ...       ...        ...   
59701   -0.242290    -0.268084   -0.292185   -0.178574 -0.223616  -0.246777   
59702   -0.242290    -0.268084   -0.292185   -0.178574 -0.223616  -0.246777   
59703   -0.242290    -0.268084   -0.292185   -0.178574 -0.223616  -0.246777   
59704   -0.242290    -0.268084   -0.292185   -0.178574 -0.223616  -0.246777   
59705   -0.242290    -0.268084   -0.292185   -0.178574 -0.223616  -0.246777   

       max_idle  std_idle  encoded_class  
0      0.545133  0.554642              0  
1      0.541502  0.495028              0  
2      0.200576  0.753111              0  
3      0.255431  0.760556              0  
4      0.380876 -0.358025              0  
...         ...       ...            ...  
59701 -0.268493 -0.162674              0  
59702 -0.268493 -0.162674              0  
59703 -0.268493 -0.162674              0  
59704 -0.268493 -0.162674              0  
59705 -0.268493 -0.162674              0  

[59706 rows x 24 columns]

In [43]:
dataNorm.dtypes

duration              float64
total_fiat            float64
total_biat            float64
min_fiat              float64
min_biat              float64
max_fiat              float64
max_biat              float64
mean_fiat             float64
mean_biat             float64
flowPktsPerSecond     float64
flowBytesPerSecond    float64
min_flowiat           float64
max_flowiat           float64
mean_flowiat          float64
std_flowiat           float64
min_active            float64
mean_active           float64
max_active            float64
std_active            float64
min_idle              float64
mean_idle             float64
max_idle              float64
std_idle              float64
encoded_class           int32
dtype: object

In [44]:
dataNorm

duration  total_fiat  total_biat  min_fiat  min_biat  max_fiat  \
0      1.387643   -0.311477   -0.276861  0.628009  0.823722 -0.411613   
1      1.433055   -0.311477   -0.276861  0.628704  0.818574 -0.409091   
2      0.876661   -0.311476   -0.276861  0.261788  0.379124 -0.376589   
3      0.396602   -0.311477   -0.276861  0.320534  0.449830 -0.396896   
4      1.441082    1.925923    2.154681  0.452196  0.613841  1.628258   
...         ...         ...         ...       ...       ...       ...   
59701 -0.675617   -0.271345   -0.269416 -0.312038 -0.296472 -0.319534   
59702 -0.677088   -0.271345   -0.269416 -0.312038 -0.296472 -0.319534   
59703 -0.675986   -0.271345   -0.269416 -0.312038 -0.296472 -0.319534   
59704 -0.658908   -0.271345   -0.269416 -0.312038 -0.296472 -0.319534   
59705 -0.675398   -0.271345   -0.269416 -0.312038 -0.296472 -0.319534   

       max_biat  mean_fiat  mean_biat  flowPktsPerSecond  ...  std_flowiat  \
0     -0.392982  -0.162273  -0.155449           0.649243  ...    -0.355567   
1     -0.394245  -0.155295  -0.162247           0.607625  ...    -0.354658   
2     -0.349008  -0.042972   0.009202           0.199013  ...    -0.263476   
3     -0.378565  -0.100082  -0.083194           0.187662  ...    -0.312051   
4      1.811737  -0.381014  -0.464994          -0.058262  ...     0.944604   
...         ...        ...        ...                ...  ...          ...   
59701 -0.369323  -0.194815  -0.243745          -0.107057  ...    -0.292869   
59702 -0.369323  -0.194815  -0.243745          -0.106477  ...    -0.292869   
59703 -0.369323  -0.194815  -0.243745          -0.106945  ...    -0.292869   
59704 -0.369323  -0.194815  -0.243745          -0.108152  ...    -0.292869   
59705 -0.369323  -0.194815  -0.243745          -0.107116  ...    -0.292869   

       min_active  mean_active  max_active  std_active  min_idle  mean_idle  \
0       -0.378909    -0.325365    0.526630    0.521968 -0.381806  -0.351999   
1       -0.376179    -0.345179    0.524956    0.468308 -0.382291  -0.360140   
2       -0.331239    -0.176311    0.190405    0.661566 -0.374314  -0.195001   
3       -0.371975    -0.201415    0.239987    0.728475 -0.377779  -0.223393   
4        0.600347     0.496862    0.359364   -0.368088  0.610032   0.508947   
...           ...          ...         ...         ...       ...        ...   
59701   -0.242290    -0.268084   -0.292185   -0.178574 -0.223616  -0.246777   
59702   -0.242290    -0.268084   -0.292185   -0.178574 -0.223616  -0.246777   
59703   -0.242290    -0.268084   -0.292185   -0.178574 -0.223616  -0.246777   
59704   -0.242290    -0.268084   -0.292185   -0.178574 -0.223616  -0.246777   
59705   -0.242290    -0.268084   -0.292185   -0.178574 -0.223616  -0.246777   

       max_idle  std_idle  encoded_class  
0      0.545133  0.554642              0  
1      0.541502  0.495028              0  
2      0.200576  0.753111              0  
3      0.255431  0.760556              0  
4      0.380876 -0.358025              0  
...         ...       ...            ...  
59701 -0.268493 -0.162674              0  
59702 -0.268493 -0.162674              0  
59703 -0.268493 -0.162674              0  
59704 -0.268493 -0.162674              0  
59705 -0.268493 -0.162674              0  

[59706 rows x 24 columns]

In [51]:
dataNorm['encoded_class'].value_counts()

1    30093
0    29613
Name: encoded_class, dtype: int64

In [48]:
df_total_numeric_features=dataNorm[['duration',
 'total_fiat',
 'total_biat',
 'min_fiat',
 'min_biat',
 'max_fiat',
 'max_biat',
 'mean_fiat',
 'mean_biat',
 'flowPktsPerSecond',
 'flowBytesPerSecond',
 'min_flowiat',
 'max_flowiat',
 'mean_flowiat',
 'std_flowiat',
 'min_active',
 'mean_active',
 'max_active',
 'std_active',
 'min_idle',
 'mean_idle',
 'max_idle',
 'std_idle']].to_numpy()

In [49]:
df_total_numeric_label=dataNorm[['encoded_class']].to_numpy()

In [50]:
ohe_label = to_categorical(df_total_numeric_label)

In [51]:
ohe_label[30000]

array([0., 1.], dtype=float32)

In [52]:
df_total_numeric_label[30000]

array([1])

In [53]:
X_train, X_test, y_train, y_test = train_test_split(df_total_numeric_features, ohe_label,
                                                    stratify=ohe_label, 
                                                    test_size=0.2)

In [54]:

(unique, counts) = np.unique(y_train, return_counts=True,axis=0)

In [55]:
unique

array([[0., 1.],
       [1., 0.]], dtype=float32)

In [56]:
counts

array([24074, 23690], dtype=int64)

In [57]:

(unique, counts) = np.unique(y_test, return_counts=True,axis=0)

In [58]:
unique

array([[0., 1.],
       [1., 0.]], dtype=float32)

In [59]:
counts

array([6019, 5923], dtype=int64)

In [60]:
total_test=len(X_test)
total_test

11942

In [61]:
total_train=len(X_train)
total_train

47764

In [62]:


np.random.seed(1000)

In [63]:
x_train, y_train = shuffle(X_train, y_train, random_state=1000)
x_test, y_test = shuffle(X_test, y_test, random_state=1000)

In [64]:
len(x_train)

47764

In [65]:
len(x_test)

11942

In [67]:
y_train=y_train.astype('int32')

In [68]:
x_train=x_train.astype('float32')

In [69]:
x_train[1].shape

(23,)

In [70]:
x_train[1]

array([-0.46668154, -0.27131087, -0.2693655 , -0.16912448, -0.13390942,
       -0.27053908, -0.29352883, -0.11285513, -0.08152592, -0.10783993,
       -0.05051036, -0.09378807, -0.16857561, -0.28026292, -0.21702717,
       -0.08585092, -0.11316845, -0.14214267, -0.17857406, -0.1098569 ,
       -0.13412452, -0.15930304, -0.16267352], dtype=float32)

In [73]:
y_test=y_test.astype('int32')

In [74]:
x_test=x_test.astype('float32')

In [75]:
Epochs=600

In [77]:
 model_1 = tf.keras.models.Sequential([
    tf.keras.layers.Input(shape=(23,)), 

    tf.keras.layers.Dense(512, activation='relu'),
    tf.keras.layers.Dense(512, activation='relu'),
    tf.keras.layers.Dense(512, activation='relu'),

    tf.keras.layers.Dropout(0.2),

    tf.keras.layers.Dense(512, activation='relu'),
    tf.keras.layers.Dense(512, activation='relu'),
    tf.keras.layers.Dense(512, activation='relu'),
    
    tf.keras.layers.Dropout(0.2),

    tf.keras.layers.Dense(512, activation='relu'),
    tf.keras.layers.Dense(512, activation='relu'),
    tf.keras.layers.Dense(512, activation='relu'),
    tf.keras.layers.Dense(14, activation='softmax')
      
    ])

In [78]:
model_1.load_weights('ScenarioB-weights-best.hdf5')

In [79]:
model_2 = tf.keras.models.Sequential([
                                           
    tf.keras.layers.Input(shape=(23,)), 

    tf.keras.layers.Dense(512, activation='relu',trainable=False),
    tf.keras.layers.Dense(512, activation='relu',trainable=False),
    tf.keras.layers.Dense(512, activation='relu',trainable=False),

    tf.keras.layers.Dropout(0.2),

    tf.keras.layers.Dense(512, activation='relu',trainable=False),
    tf.keras.layers.Dense(512, activation='relu',trainable=False),
    tf.keras.layers.Dense(512, activation='relu',trainable=False),
    
    tf.keras.layers.Dropout(0.2),

    tf.keras.layers.Dense(512, activation='relu'),
    tf.keras.layers.Dense(512, activation='relu'),
    tf.keras.layers.Dense(512, activation='relu'),
    tf.keras.layers.Dense(2, activation='softmax')

])



In [80]:
model_2_baseline = tf.keras.models.Sequential([
                                           
    tf.keras.layers.Input(shape=(23,)), 

    tf.keras.layers.Dense(512, activation='relu'),
    tf.keras.layers.Dense(512, activation='relu'),
    tf.keras.layers.Dense(512, activation='relu'),

    tf.keras.layers.Dropout(0.2),

    tf.keras.layers.Dense(512, activation='relu'),
    tf.keras.layers.Dense(512, activation='relu'),
    tf.keras.layers.Dense(512, activation='relu'),
    
    tf.keras.layers.Dropout(0.2),

    tf.keras.layers.Dense(512, activation='relu'),
    tf.keras.layers.Dense(512, activation='relu'),
    tf.keras.layers.Dense(512, activation='relu'),
    tf.keras.layers.Dense(2, activation='softmax')

])

In [81]:
model_2.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_10 (Dense)             (None, 512)               12288     
_________________________________________________________________
dense_11 (Dense)             (None, 512)               262656    
_________________________________________________________________
dense_12 (Dense)             (None, 512)               262656    
_________________________________________________________________
dropout_2 (Dropout)          (None, 512)               0         
_________________________________________________________________
dense_13 (Dense)             (None, 512)               262656    
_________________________________________________________________
dense_14 (Dense)             (None, 512)               262656    
_________________________________________________________________
dense_15 (Dense)             (None, 512)              

In [82]:
model_2_baseline.summary()

Model: "sequential_2"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_20 (Dense)             (None, 512)               12288     
_________________________________________________________________
dense_21 (Dense)             (None, 512)               262656    
_________________________________________________________________
dense_22 (Dense)             (None, 512)               262656    
_________________________________________________________________
dropout_4 (Dropout)          (None, 512)               0         
_________________________________________________________________
dense_23 (Dense)             (None, 512)               262656    
_________________________________________________________________
dense_24 (Dense)             (None, 512)               262656    
_________________________________________________________________
dense_25 (Dense)             (None, 512)              

In [83]:
for i in [0,1,2,4,5,6]:
    model_2.layers[i].set_weights(model_1.layers[i].get_weights())


In [ ]:
model_2.get_weights()

In [84]:
loss_fn=tf.keras.losses.CategoricalCrossentropy()

In [85]:
model_2.compile(optimizer='sgd',
              loss=loss_fn,
              metrics=[tf.keras.metrics.CategoricalAccuracy()])

In [86]:
model_2_baseline.compile(optimizer='sgd',
              loss=loss_fn,
              metrics=[tf.keras.metrics.CategoricalAccuracy()])

In [88]:
from tensorflow.keras.callbacks import ModelCheckpoint 

In [89]:
filepath="ScenarioAmt-weights-best.hdf5"

In [91]:
checkpoint = ModelCheckpoint(filepath, monitor='val_categorical_accuracy', verbose=1, save_best_only=True, mode='max')
callbacks_list = [checkpoint]

In [ ]:
start = time.time()
model_2_fitted=model_2.fit(x_train, y_train, batch_size=100, epochs=Epochs, validation_data=(x_test, y_test), callbacks=callbacks_list, verbose=0)
end = time.time()
print(end - start)
model2_trainig_time=end - start

Epoch 00001: val_categorical_accuracy improved from -inf to 0.xxx, saving model to ScenarioAmt-weights-best.hdf5

Epoch 00002: val_categorical_accuracy improved from 0.xxx to 0.xxx, saving model to ScenarioAmt-weights-best.hdf5

Epoch 00003: val_categorical_accuracy improved from 0.xxx to 0.xxx, saving model to ScenarioAmt-weights-best.hdf5

Epoch 00004: val_categorical_accuracy improved from 0.xxx to 0.xxx, saving model to ScenarioAmt-weights-best.hdf5

In [102]:
filepath="ScenarioAmb-weights-best.hdf5"

In [103]:
checkpoint = ModelCheckpoint(filepath, monitor='val_categorical_accuracy', verbose=1, save_best_only=True, mode='max')
callbacks_list = [checkpoint]

In [ ]:
start = time.time()
model_2_baseline_fitted=model_2_baseline.fit(x_train, y_train, batch_size=100, epochs=Epochs, validation_data=(x_test, y_test), callbacks=callbacks_list, verbose=0)
end = time.time()
print(end - start)
model2_base_trainig_time= end - start

Epoch 00001: val_categorical_accuracy improved from -inf to 0.xxx, saving model to ScenarioAmb-weights-best.hdf5

Epoch 00002: val_categorical_accuracy improved from 0.xxx to 0.xxx, saving model to ScenarioAmb-weights-best.hdf5

Epoch 00003: val_categorical_accuracy did not improve from 0.xxx

Epoch 00004: val_categorical_accuracy improved from 0.xxx to 0.xxx, saving model to ScenarioAmb-weights-best.hdf5

Epoch 00005: val_categorical_accuracy improved from 0.xxx to 0.xxx, saving model to ScenarioAmb-weights-best.hdf5

In [97]:
from sklearn.metrics import classification_report

In [98]:
y_pred = model_2.predict(x_test)

In [99]:
y_pred_bool = np.argmax(y_pred, axis=1)

In [100]:
y_test_bool = np.argmax(y_test, axis=1)

In [ ]:
print(classification_report(y_test_bool, y_pred_bool))

```
                precision    recall  f1-score   support

           0       0.92      0.89      0.91      5923
           1       0.90      0.93      0.91      6019

    accuracy                           0.91     11942
   macro avg       0.91      0.91      0.91     11942
weighted avg       0.91      0.91      0.91     11942
```

In [112]:
y_pred = model_2_baseline.predict(x_test)

In [113]:
y_pred_bool = np.argmax(y_pred, axis=1)

In [114]:
y_test_bool = np.argmax(y_test, axis=1)

In [ ]:
print(classification_report(y_test_bool, y_pred_bool))

```
                precision    recall  f1-score   support

           0       0.82      0.88      0.85      5923
           1       0.87      0.80      0.83      6019

    accuracy                           0.84     11942
   macro avg       0.84      0.84      0.84     11942
weighted avg       0.84      0.84      0.84     11942
```

``` python
import matplotlib.pyplot as plt

plt.figure(figsize=(7,5))
plt.plot(t, model_2_fitted.history['val_categorical_accuracy'][:display_epoch], 'r',t, model_2_fitted.history['categorical_accuracy'][:display_epoch], 'g', t, model_2_baseline_fitted.history['val_categorical_accuracy'][:display_epoch], 'b',t, model_2_baseline_fitted.history['categorical_accuracy'][:display_epoch], 'k',)
plt.ylabel('Categorical Accuracy')
plt.xticks(np.arange(0, display_epoch+1, 100))
plt.legend([r'Training Accuracy $M_T$',r'Validation Accuracy $M_T$', r'Training Accuracy $M_B$',r'Validation Accuracy $M_B$'])
plt.show()
```

<p style="text-align:center">
    "    <img src="ScenarioA.png" width="600">
</p>
